version: '3.6'

services:

  postgres-database:
    hostname: pgdatabase
    build:
      context: ./jacah_database
    restart: always
    ports:
      - 5443:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "jacah_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  elixir-api:
    depends_on:
      - postgres-database
    build:
      context: ./jacah_backend
      args:
        - MIX_ENV=${MIX_ENV}
        - RUN_DATABASE_SETUP=${RUN_DATABASE_SETUP}
    restart: always
    ports:
      - 4000:4000
      - 4001:4001
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: pgdatabase
      POSTGRES_PORT: ${POSTGRES_PORT}
      DEBUG: 1
