version: '3.6'

services:

  postgres-database:
    build: ./jacah_database
    restart: always
    ports:
      - 5443:5432
    environment:
      POSTGRES_USER: jacah_user
      POSTGRES_PASSWORD: 123456sete
      POSTGRES_DB: jacah_db

  elixir-api:
    build: ./jacah_backend
    restart: always
    environment:
      DEBUG: 1
      POSTGRES_USER: jacah_user
      POSTGRES_PASSWORD: 123456sete
      POSTGRES_ADDRESS: postgres-database
      POSTGRES_DB: jacah_db
      POSTGRES_PORT: 5432
